spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/mq_db
    username: mq_user
    password: mq_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
